dataset_path: ../datasets/N1000_T300_steps600_zeros_knoise0.0_reduced11_ABCDEFGHIJM.npz
exp_name: reduced11_100ep_lr1e-3_substeps20_1layer

epochs: 100
batch_size: 1000
lr: 0.001
weight_decay: 0.0085
val_frac: 0.15
seed: 42

hidden: 128
num_layers: 1
grad_clip: 1.0

teacher_forcing: true
tf_every: 50
tf_drop_epoch: 250

scaffold: reduced11

theta_lo: 1.0e-3
theta_hi: 2.0

n_substeps: 20
